// ============================================================
// Design tokens & inline styles
// Migré tel quel du monolithe pour ne rien casser visuellement.
// À terme : à convertir en CSS modules ou en système de tokens.
// ============================================================

export const globalCSS = `
  @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;700;800&family=Manrope:wght@400;500;600;700;800&display=swap');
  * { box-sizing: border-box; -webkit-tap-highlight-color: transparent; }
  body { margin: 0; padding: 0; background: #050810; font-family: 'Manrope', system-ui, sans-serif; }
  button { cursor: pointer; font-family: inherit; }
  input, select, textarea { font-family: inherit; outline: none; }
  @keyframes pulse {
    0%, 100% { opacity: 1; transform: scale(1); }
    50% { opacity: 0.6; transform: scale(1.4); }
  }
  @keyframes slideUp {
    from { opacity: 0; transform: translateY(8px); }
    to { opacity: 1; transform: translateY(0); }
  }
  @keyframes shimmer {
    0% { background-position: -200% 0; }
    100% { background-position: 200% 0; }
  }
  @keyframes scanLine {
    0% { top: 16px; }
    50% { top: calc(100% - 18px); }
    100% { top: 16px; }
  }
  @keyframes scrollLeft {
    0% { transform: translateX(0); }
    100% { transform: translateX(-33.333%); }
  }
  ::-webkit-scrollbar { width: 0; }
`;

export const styles = {
  app: {
    minHeight: '100vh',
    background: '#050810',
    color: '#f1f5f9',
    fontFamily: "'Manrope', system-ui, sans-serif",
    position: 'relative',
    maxWidth: 480,
    margin: '0 auto',
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 0,
    paddingBottom: 0,
    boxSizing: 'border-box',
  },
  bgGrid: {
    position: 'fixed', inset: 0,
    backgroundImage: 'linear-gradient(rgba(34,211,238,0.04) 1px, transparent 1px), linear-gradient(90deg, rgba(34,211,238,0.04) 1px, transparent 1px)',
    backgroundSize: '32px 32px',
    pointerEvents: 'none',
    maskImage: 'radial-gradient(ellipse at center top, black 30%, transparent 80%)',
  },
  bgGlow1: {
    position: 'fixed', top: -200, left: -100, width: 400, height: 400,
    background: 'radial-gradient(circle, rgba(34,211,238,0.15), transparent 70%)',
    pointerEvents: 'none',
  },
  bgGlow2: {
    position: 'fixed', bottom: -200, right: -100, width: 400, height: 400,
    background: 'radial-gradient(circle, rgba(167,139,250,0.12), transparent 70%)',
    pointerEvents: 'none',
  },
  topbar: {
    position: 'sticky', top: 0, zIndex: 50,
    display: 'flex', justifyContent: 'space-between', alignItems: 'center',
    padding: '14px 16px',
    background: 'rgba(5,8,16,0.85)',
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
    borderBottom: '1px solid rgba(34,211,238,0.12)',
  },
  topbarLeft: { display: 'flex', alignItems: 'center', gap: 10 },
  topbarRight: { display: 'flex', alignItems: 'center', gap: 8 },
  logo: { display: 'flex', alignItems: 'center', gap: 10 },
  logoMark: {
    width: 32, height: 32, borderRadius: 8,
    background: 'linear-gradient(135deg, #a3e635, #67e8f9)',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    boxShadow: '0 0 24px rgba(34,211,238,0.4), inset 0 1px 0 rgba(255,255,255,0.3)',
  },
  logoName: { fontSize: 14, fontWeight: 900, letterSpacing: 3, color: '#f1f5f9', lineHeight: 1 },
  logoSub: { fontSize: 8, fontWeight: 600, letterSpacing: 2, color: '#64748b', textTransform: 'uppercase', marginTop: 2 },
  liveDot: {
    display: 'flex', alignItems: 'center', gap: 5,
    fontSize: 9, fontWeight: 800, letterSpacing: 1.5, color: '#a3e635',
    padding: '4px 8px',
    background: 'rgba(34,211,238,0.08)',
    border: '1px solid rgba(34,211,238,0.3)',
    borderRadius: 4,
  },
  dot: {
    width: 6, height: 6, borderRadius: '50%',
    background: '#a3e635',
    animation: 'pulse 1.5s ease-in-out infinite',
  },
  pulseDot: {
    position: 'absolute', top: 6, right: 6,
    width: 8, height: 8, borderRadius: '50%',
    animation: 'pulse 1.5s ease-in-out infinite',
    boxShadow: '0 0 0 2px rgba(15,23,42,0.8)',
  },
  roleBadge: {
    display: 'flex', alignItems: 'center', gap: 5,
    padding: '5px 9px',
    background: 'rgba(15,23,42,0.6)',
    border: '1px solid',
    borderRadius: 6,
  },
  main: { padding: '16px', position: 'relative', zIndex: 1 },
  hero: {
    position: 'relative',
    background: 'linear-gradient(135deg, rgba(15,23,42,0.8), rgba(15,23,42,0.4))',
    border: '1px solid rgba(34,211,238,0.25)',
    borderRadius: 16,
    padding: 18,
    overflow: 'hidden',
    marginBottom: 14,
    animation: 'slideUp 0.4s ease',
  },
  heroGrid: { position: 'relative', zIndex: 2 },
  heroLabel: {
    display: 'inline-flex', alignItems: 'center', gap: 4,
    fontSize: 9, fontWeight: 800, letterSpacing: 2, color: '#a3e635',
    padding: '3px 8px',
    background: 'rgba(34,211,238,0.1)',
    border: '1px solid rgba(34,211,238,0.3)',
    borderRadius: 4,
    marginBottom: 12,
  },
  heroTitle: {
    fontSize: 22, fontWeight: 800, letterSpacing: -0.5, color: '#f1f5f9',
    lineHeight: 1.1, marginBottom: 10,
    fontFamily: "'Manrope', sans-serif",
  },
  heroMeta: {
    display: 'flex', flexDirection: 'column', gap: 4,
    fontSize: 11, color: '#94a3b8', fontWeight: 500,
    marginBottom: 14,
  },
  heroProgress: { display: 'flex', flexDirection: 'column', gap: 6 },
  progressTrack: { height: 6, background: 'rgba(15,23,42,0.8)', borderRadius: 3, overflow: 'hidden' },
  progressFill: {
    height: '100%',
    background: 'linear-gradient(90deg, #a3e635, #67e8f9)',
    borderRadius: 3,
    transition: 'width 0.6s ease',
    boxShadow: '0 0 12px rgba(34,211,238,0.5)',
  },
  progressMeta: { display: 'flex', gap: 4, fontSize: 11, fontFamily: "'JetBrains Mono', monospace" },
  heroAccent: {
    position: 'absolute', top: -50, right: -50, width: 200, height: 200,
    background: 'radial-gradient(circle, rgba(34,211,238,0.2), transparent 60%)',
  },
  statRow: { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 8, marginBottom: 18 },
  statTile: {
    background: 'rgba(15,23,42,0.5)',
    border: '1px solid rgba(34,211,238,0.1)',
    borderRadius: 10,
    padding: '10px 6px',
    textAlign: 'center',
    position: 'relative',
  },
  statValue: {
    fontSize: 22, fontWeight: 800, lineHeight: 1,
    fontFamily: "'JetBrains Mono', monospace",
    position: 'relative', display: 'inline-block',
  },
  statLabel: {
    fontSize: 8, fontWeight: 700, letterSpacing: 1, color: '#64748b',
    marginTop: 6, textTransform: 'uppercase',
  },
  section: { marginBottom: 18 },
  sectionHeader: {
    display: 'flex', justifyContent: 'space-between', alignItems: 'center',
    marginBottom: 10, padding: '0 2px',
  },
  sectionIconBox: {
    width: 22, height: 22, borderRadius: 5,
    border: '1px solid', display: 'flex', alignItems: 'center', justifyContent: 'center',
  },
  sectionTitle: {
    fontSize: 11, fontWeight: 800, letterSpacing: 1.5, color: '#cbd5e1', textTransform: 'uppercase',
  },
  sectionBadge: {
    fontSize: 9, fontWeight: 800, color: '#0a0a0a',
    padding: '2px 6px', borderRadius: 10, marginLeft: 4,
  },
  cardStack: { display: 'flex', flexDirection: 'column', gap: 8 },
  matchCard: {
    background: 'rgba(15,23,42,0.5)',
    border: '1px solid rgba(34,211,238,0.1)',
    borderRadius: 12,
    padding: 0,
    width: '100%',
    textAlign: 'left',
    transition: 'all 0.2s',
    overflow: 'hidden',
  },
  matchHeader: {
    display: 'flex', justifyContent: 'space-between', alignItems: 'center',
    padding: '8px 12px',
    borderBottom: '1px solid rgba(255,255,255,0.04)',
  },
  matchMeta: {
    fontSize: 9, fontWeight: 700, color: '#64748b', letterSpacing: 0.5, textTransform: 'uppercase',
    display: 'inline-flex', alignItems: 'center', gap: 3,
  },
  matchTime: {
    fontSize: 10, fontWeight: 700, color: '#94a3b8', letterSpacing: 0.5,
    display: 'inline-flex', alignItems: 'center', gap: 3,
    fontFamily: "'JetBrains Mono', monospace",
  },
  liveBadge: {
    display: 'inline-flex', alignItems: 'center',
    fontSize: 9, fontWeight: 800, letterSpacing: 1, color: '#a3e635',
    padding: '2px 6px',
    background: 'rgba(34,211,238,0.12)',
    border: '1px solid rgba(34,211,238,0.4)',
    borderRadius: 3,
  },
  pendingBadge: {
    display: 'inline-flex', alignItems: 'center', gap: 3,
    fontSize: 9, fontWeight: 800, letterSpacing: 1, color: '#f59e0b',
    padding: '2px 6px',
    background: 'rgba(245,158,11,0.12)',
    border: '1px solid rgba(245,158,11,0.4)',
    borderRadius: 3,
  },
  validatedBadge: {
    display: 'inline-flex', alignItems: 'center', gap: 3,
    fontSize: 9, fontWeight: 800, letterSpacing: 1, color: '#34d399',
    padding: '2px 6px',
    background: 'rgba(52,211,153,0.12)',
    border: '1px solid rgba(52,211,153,0.4)',
    borderRadius: 3,
  },
  matchBody: {
    display: 'grid',
    gridTemplateColumns: '1fr auto 1fr',
    alignItems: 'center', gap: 10,
    padding: '14px 12px',
  },
  teamSide: { display: 'flex', alignItems: 'center', gap: 8, minWidth: 0 },
  teamCrest: {
    width: 36, height: 36, borderRadius: 8,
    border: '1.5px solid', display: 'flex', alignItems: 'center', justifyContent: 'center',
    fontSize: 11, fontWeight: 800, letterSpacing: 0.5, flexShrink: 0,
    fontFamily: "'JetBrains Mono', monospace",
  },
  teamCrestSmall: {
    width: 26, height: 26, borderRadius: 6,
    border: '1.5px solid', display: 'flex', alignItems: 'center', justifyContent: 'center',
    fontSize: 9, fontWeight: 800, letterSpacing: 0.3, flexShrink: 0,
    fontFamily: "'JetBrains Mono', monospace",
  },
  teamCrestLarge: {
    width: 44, height: 44, borderRadius: 10,
    border: '2px solid', display: 'flex', alignItems: 'center', justifyContent: 'center',
    fontSize: 13, fontWeight: 800, letterSpacing: 0.5, flexShrink: 0,
    fontFamily: "'JetBrains Mono', monospace",
  },
  teamName: { fontSize: 12, fontWeight: 700, color: '#f1f5f9', lineHeight: 1.1 },
  teamShort: { fontSize: 9, fontWeight: 600, color: '#64748b', letterSpacing: 0.5, fontFamily: "'JetBrains Mono', monospace" },
  teamNameSmall: { fontSize: 12, fontWeight: 700, color: '#f1f5f9', lineHeight: 1.1 },
  scoreBox: {
    display: 'flex', alignItems: 'center', gap: 6,
    padding: '6px 10px',
    background: 'rgba(0,0,0,0.3)',
    borderRadius: 8,
    border: '1px solid rgba(255,255,255,0.05)',
  },
  scoreLive: {
    fontSize: 22, fontWeight: 800, color: '#a3e635',
    fontFamily: "'JetBrains Mono', monospace",
    textShadow: '0 0 12px rgba(34,211,238,0.4)',
  },
  scoreFinal: {
    fontSize: 22, fontWeight: 800, color: '#f1f5f9',
    fontFamily: "'JetBrains Mono', monospace",
  },
  scoreUpcoming: {
    fontSize: 11, fontWeight: 800, color: '#475569', letterSpacing: 1,
    fontFamily: "'JetBrains Mono', monospace",
  },
  scoreSep: { fontSize: 18, fontWeight: 800, color: '#475569' },
  matchFooter: {
    display: 'flex', alignItems: 'center', gap: 4,
    padding: '8px 12px',
    fontSize: 9, color: '#64748b', fontWeight: 600,
    borderTop: '1px solid rgba(255,255,255,0.04)',
  },
  btnValidate: {
    display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: 6,
    padding: '10px 12px',
    background: 'linear-gradient(135deg, #a3e635, #84cc16)',
    color: '#0a0a0a',
    border: 'none', borderRadius: 8,
    fontSize: 11, fontWeight: 800, letterSpacing: 1,
    boxShadow: '0 0 20px rgba(34,211,238,0.3)',
  },
  btnReject: {
    display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: 6,
    padding: '10px 12px',
    background: 'rgba(15,23,42,0.6)',
    color: '#94a3b8',
    border: '1px solid rgba(255,255,255,0.08)', borderRadius: 8,
    fontSize: 11, fontWeight: 800, letterSpacing: 1,
  },
  bottomNav: {
    position: 'fixed', bottom: 0, left: '50%', transform: 'translateX(-50%)',
    width: 'calc(100% - 32px)', maxWidth: 448,
    marginBottom: 8,
    borderRadius: 14,
    display: 'flex', justifyContent: 'space-around',
    padding: '8px 0',
    background: 'rgba(5,8,16,0.92)',
    backdropFilter: 'blur(24px)',
    WebkitBackdropFilter: 'blur(24px)',
    borderTop: '1px solid rgba(34,211,238,0.12)',
    zIndex: 50,
  },
  navBtn: {
    flex: 1, position: 'relative',
    display: 'flex', flexDirection: 'column', alignItems: 'center',
    padding: '8px 4px',
    background: 'transparent', border: 'none',
    color: '#64748b',
  },
  navBtnActive: { color: '#a3e635' },
  navIndicator: {
    position: 'absolute', bottom: 0, left: '30%', right: '30%',
    height: 2, background: '#a3e635', borderRadius: '2px 2px 0 0',
    boxShadow: '0 0 12px #a3e635',
  },
  pageHeader: {
    display: 'flex', alignItems: 'center', gap: 12,
    marginBottom: 18, padding: '4px 0',
    animation: 'slideUp 0.4s ease',
  },
  pageIcon: {
    width: 36, height: 36, borderRadius: 9,
    border: '1px solid', display: 'flex', alignItems: 'center', justifyContent: 'center',
  },
  pageTitle: { fontSize: 20, fontWeight: 800, letterSpacing: -0.5, color: '#f1f5f9', lineHeight: 1.1 },
  pageSubtitle: { fontSize: 11, color: '#64748b', marginTop: 3, fontWeight: 500 },
  poolTabs: {
    display: 'flex', gap: 6, marginBottom: 12,
  },
  poolTab: {
    flex: 1, padding: '10px 12px',
    background: 'rgba(15,23,42,0.5)',
    border: '1px solid rgba(255,255,255,0.06)',
    borderRadius: 8,
    fontSize: 11, fontWeight: 800, letterSpacing: 1.5, color: '#64748b',
  },
  poolTabActive: {
    background: 'rgba(245,158,11,0.1)',
    borderColor: 'rgba(245,158,11,0.4)',
    color: '#f59e0b',
  },
  standingsCard: {
    background: 'rgba(15,23,42,0.4)',
    border: '1px solid rgba(255,255,255,0.06)',
    borderRadius: 12, overflow: 'hidden',
  },
  standingsHead: {
    display: 'flex', alignItems: 'center', gap: 6,
    padding: '10px 12px',
    background: 'rgba(0,0,0,0.3)',
    fontSize: 9, fontWeight: 800, letterSpacing: 1, color: '#475569',
    fontFamily: "'JetBrains Mono', monospace",
    borderBottom: '1px solid rgba(255,255,255,0.04)',
  },
  standingsRow: {
    display: 'flex', alignItems: 'center', gap: 6,
    padding: '12px',
    borderBottom: '1px solid rgba(255,255,255,0.04)',
  },
  statCol: {
    width: 24, textAlign: 'center',
    fontSize: 12, fontWeight: 700, color: '#cbd5e1',
    fontFamily: "'JetBrains Mono', monospace",
  },
  bonusLine: { fontSize: 9, color: '#facc15', fontWeight: 600, marginTop: 1 },
  tieRules: {
    marginTop: 14, padding: 12,
    background: 'rgba(15,23,42,0.4)',
    border: '1px solid rgba(255,255,255,0.04)',
    borderRadius: 10,
  },
  tieRulesTitle: {
    display: 'flex', alignItems: 'center', gap: 6,
    fontSize: 9, fontWeight: 800, letterSpacing: 1.5, color: '#64748b',
    marginBottom: 8,
  },
  tieRulesList: { display: 'flex', flexDirection: 'column', gap: 6 },
  tieRule: { display: 'flex', alignItems: 'center', gap: 8, fontSize: 11, color: '#cbd5e1', fontWeight: 500 },
  tieRuleNum: {
    width: 18, height: 18, borderRadius: 4,
    background: 'rgba(34,211,238,0.1)', border: '1px solid rgba(34,211,238,0.3)',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    fontSize: 9, fontWeight: 800, color: '#a3e635',
    fontFamily: "'JetBrains Mono', monospace",
    flexShrink: 0,
  },
  filterBar: {
    display: 'flex', gap: 6, marginBottom: 12, overflowX: 'auto', paddingBottom: 4,
  },
  filterChip: {
    padding: '7px 12px', flexShrink: 0,
    background: 'rgba(15,23,42,0.5)',
    border: '1px solid rgba(255,255,255,0.06)',
    borderRadius: 6,
    fontSize: 10, fontWeight: 800, letterSpacing: 1, color: '#64748b',
  },
  filterChipActive: {
    background: 'rgba(34,211,238,0.1)',
    borderColor: 'rgba(34,211,238,0.4)',
    color: '#a3e635',
  },
  emptyState: {
    display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 10,
    padding: 40, color: '#475569', fontSize: 12,
  },
  backBtn: {
    display: 'inline-flex', alignItems: 'center', gap: 6,
    padding: '6px 10px',
    background: 'rgba(15,23,42,0.5)',
    border: '1px solid rgba(255,255,255,0.06)',
    borderRadius: 6,
    fontSize: 11, fontWeight: 700, color: '#94a3b8',
    marginBottom: 14,
  },
  matchDetailHero: {
    background: 'linear-gradient(135deg, rgba(15,23,42,0.8), rgba(15,23,42,0.3))',
    border: '1px solid rgba(34,211,238,0.2)',
    borderRadius: 16,
    padding: '18px 14px',
    marginBottom: 14,
  },
  matchMetaRow: {
    display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6,
    marginBottom: 10,
  },
  matchDot: { color: '#475569', fontSize: 10 },
  statusPill: {
    display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 5,
    width: 'fit-content', margin: '0 auto 16px',
    padding: '4px 10px',
    border: '1px solid', borderRadius: 12,
    fontSize: 9, fontWeight: 800, letterSpacing: 1.5,
  },
  bigScore: {
    display: 'grid',
    gridTemplateColumns: '1fr auto 1fr',
    alignItems: 'center', gap: 10,
    padding: '10px 0',
  },
  bigTeam: {
    display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8,
  },
  bigCrest: {
    width: 56, height: 56, borderRadius: 12,
    border: '2px solid', display: 'flex', alignItems: 'center', justifyContent: 'center',
    fontSize: 18, fontWeight: 800, letterSpacing: 1,
    fontFamily: "'JetBrains Mono', monospace",
  },
  bigTeamName: {
    fontSize: 12, fontWeight: 700, color: '#f1f5f9', textAlign: 'center', lineHeight: 1.2,
  },
  bigScoreNumbers: {
    display: 'flex', alignItems: 'center', gap: 6,
  },
  bigScoreNum: {
    fontSize: 44, fontWeight: 800,
    fontFamily: "'JetBrains Mono', monospace",
    lineHeight: 1,
  },
  bigScoreSep: {
    fontSize: 32, fontWeight: 600, color: '#334155',
    fontFamily: "'JetBrains Mono', monospace",
  },
  scoreEditor: { display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 4 },
  scoreBtn: {
    background: 'transparent', border: 'none', padding: 4,
    color: 'currentColor', opacity: 0.7,
  },
  refRow: {
    display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 5,
    fontSize: 10, color: '#64748b', fontWeight: 600,
    marginTop: 12, paddingTop: 10,
    borderTop: '1px solid rgba(255,255,255,0.06)',
  },
  detailCard: {
    background: 'rgba(15,23,42,0.5)',
    border: '1px solid rgba(255,255,255,0.06)',
    borderRadius: 12,
    padding: 14, marginBottom: 12,
  },
  detailCardTitle: {
    display: 'flex', alignItems: 'center', gap: 6,
    fontSize: 10, fontWeight: 800, letterSpacing: 1.5, color: '#cbd5e1',
    marginBottom: 12,
  },
  fpRow: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 },
  fpToggle: {
    display: 'flex', alignItems: 'center', gap: 8,
    padding: 10,
    border: '1px solid', borderRadius: 8,
    transition: 'all 0.2s',
  },
  fpLabel: { flex: 1, fontSize: 11, fontWeight: 700, color: '#cbd5e1', textAlign: 'left' },
  fpHint: { fontSize: 10, color: '#64748b', marginTop: 8, textAlign: 'center' },
  actionStack: { display: 'flex', flexDirection: 'column', gap: 8 },
  btnPrimary: {
    display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: 8,
    width: '100%', padding: '14px',
    background: 'linear-gradient(135deg, #a3e635, #84cc16)',
    color: '#0a0a0a', border: 'none', borderRadius: 10,
    fontSize: 12, fontWeight: 800, letterSpacing: 1.5,
    boxShadow: '0 0 30px rgba(34,211,238,0.3)',
  },
  btnSecondary: {
    display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: 6,
    width: '100%', padding: '12px',
    background: 'rgba(15,23,42,0.6)',
    color: '#cbd5e1', border: '1px solid rgba(255,255,255,0.1)',
    borderRadius: 10,
    fontSize: 11, fontWeight: 700, letterSpacing: 1,
  },
  btnDanger: {
    display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: 6,
    width: '100%', padding: '11px',
    background: 'rgba(220,38,38,0.1)',
    color: '#f87171', border: '1px solid rgba(220,38,38,0.3)',
    borderRadius: 8,
    fontSize: 11, fontWeight: 700, letterSpacing: 1,
  },
  infoBox: {
    display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6,
    padding: 12,
    background: 'rgba(15,23,42,0.5)',
    border: '1px solid rgba(255,255,255,0.06)',
    borderRadius: 10,
    fontSize: 11, color: '#94a3b8', fontWeight: 600,
  },
  teamCard: {
    display: 'flex', alignItems: 'center', gap: 12,
    padding: 12,
    background: 'rgba(15,23,42,0.5)',
    border: '1px solid rgba(255,255,255,0.06)',
    borderRadius: 12,
  },
  teamCardLeft: {
    display: 'flex', alignItems: 'center', gap: 12,
    flex: 1, minWidth: 0,
    background: 'transparent', border: 'none', padding: 0,
  },
  teamCardName: { fontSize: 13, fontWeight: 700, color: '#f1f5f9' },
  teamCardShort: { fontSize: 10, color: '#64748b', marginTop: 2, fontWeight: 600, fontFamily: "'JetBrains Mono', monospace" },
  btnAddTeam: {
    display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8,
    width: '100%', padding: '12px',
    background: 'rgba(167,139,250,0.08)',
    border: '1.5px dashed rgba(167,139,250,0.4)',
    borderRadius: 12,
    color: '#818cf8',
    fontSize: 11, fontWeight: 800, letterSpacing: 1.5,
    marginBottom: 16,
  },
  btnSmall: {
    display: 'inline-flex', alignItems: 'center', gap: 4,
    padding: '8px 12px',
    background: 'rgba(15,23,42,0.6)',
    border: '1px solid rgba(255,255,255,0.08)',
    borderRadius: 8,
    color: '#94a3b8',
    fontSize: 10, fontWeight: 700, letterSpacing: 0.5,
  },
  btnDangerSmall: {
    display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
    width: 42, padding: '11px',
    background: 'rgba(220,38,38,0.1)',
    color: '#f87171', border: '1px solid rgba(220,38,38,0.3)',
    borderRadius: 8,
  },
  modalOverlay: {
    position: 'fixed', inset: 0, zIndex: 100,
    background: 'rgba(0,0,0,0.7)',
    backdropFilter: 'blur(8px)',
    WebkitBackdropFilter: 'blur(8px)',
    display: 'flex', alignItems: 'flex-end', justifyContent: 'center',
    animation: 'slideUp 0.2s ease',
  },
  modalCard: {
    width: '100%', maxWidth: 480,
    background: '#0a0f1c',
    border: '1px solid rgba(34,211,238,0.2)',
    borderRadius: '16px 16px 0 0',
    maxHeight: '92vh',
    display: 'flex', flexDirection: 'column',
    boxShadow: '0 -20px 60px rgba(0,0,0,0.6)',
  },
  modalHead: {
    display: 'flex', justifyContent: 'space-between', alignItems: 'center',
    padding: '14px 16px',
    borderBottom: '1px solid rgba(255,255,255,0.06)',
    flexShrink: 0,
  },
  modalTitle: {
    fontSize: 14, fontWeight: 800, letterSpacing: 0.5, color: '#f1f5f9',
  },
  modalClose: {
    width: 28, height: 28, borderRadius: 6,
    background: 'rgba(15,23,42,0.6)',
    border: '1px solid rgba(255,255,255,0.08)',
    color: '#94a3b8',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
  },
  modalBody: {
    padding: 16,
    overflowY: 'auto',
    flex: 1,
    minHeight: 0,
    display: 'flex', flexDirection: 'column', gap: 12,
  },
  modalFooter: {
    display: 'flex', gap: 8,
    padding: 14,
    borderTop: '1px solid rgba(255,255,255,0.06)',
    flexShrink: 0,
    background: '#0a0f1c',
  },
  fullscreenSheet: {
    position: 'fixed', inset: 0, zIndex: 200,
    background: '#050810',
    display: 'flex', flexDirection: 'column',
    maxWidth: 480, margin: '0 auto',
    animation: 'slideUp 0.25s ease',
  },
  sheetHead: {
    display: 'grid',
    gridTemplateColumns: 'auto 1fr auto',
    alignItems: 'center', gap: 10,
    padding: '14px 16px',
    background: 'rgba(5,8,16,0.95)',
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
    borderBottom: '1px solid rgba(34,211,238,0.18)',
    flexShrink: 0,
    position: 'sticky', top: 0, zIndex: 2,
  },
  sheetBack: {
    width: 34, height: 34, borderRadius: 8,
    background: 'rgba(15,23,42,0.6)',
    border: '1px solid rgba(255,255,255,0.08)',
    color: '#cbd5e1',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
  },
  sheetTitle: {
    fontSize: 14, fontWeight: 800, letterSpacing: 0.3, color: '#f1f5f9',
    textAlign: 'center',
  },
  sheetSave: {
    padding: '9px 14px',
    background: 'linear-gradient(135deg, #a3e635, #84cc16)',
    color: '#0a0a0a',
    border: 'none', borderRadius: 8,
    fontSize: 11, fontWeight: 800, letterSpacing: 1.2,
    boxShadow: '0 0 20px rgba(34,211,238,0.3)',
  },
  sheetBody: {
    flex: 1,
    overflowY: 'auto',
    padding: 16,
    display: 'flex', flexDirection: 'column', gap: 12,
    paddingBottom: 80,
  },
  previewCrest: {
    display: 'flex', flexDirection: 'column', alignItems: 'center',
    padding: '14px',
    background: 'rgba(0,0,0,0.3)',
    border: '1px solid rgba(255,255,255,0.04)',
    borderRadius: 10,
    marginBottom: 4,
  },
  colorGrid: {
    display: 'grid', gridTemplateColumns: 'repeat(6, 1fr)', gap: 6,
  },
  colorSwatch: {
    aspectRatio: '1', padding: 0,
    border: '1.5px solid', borderRadius: 8,
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    transition: 'all 0.15s',
  },
  extraPointsCtrl: {
    display: 'flex', alignItems: 'center', gap: 4,
    padding: '4px',
    background: 'rgba(0,0,0,0.3)',
    border: '1px solid rgba(250,204,21,0.2)',
    borderRadius: 8,
  },
  epBtn: {
    background: 'transparent', border: 'none',
    color: '#94a3b8', padding: 4, display: 'flex',
  },
  epValue: { display: 'flex', flexDirection: 'column', alignItems: 'center', minWidth: 40 },
  extraPointsDisplay: {
    display: 'flex', alignItems: 'center', gap: 3,
    padding: '4px 8px',
    background: 'rgba(250,204,21,0.1)',
    border: '1px solid rgba(250,204,21,0.3)',
    borderRadius: 6,
  },
  helpBox: {
    display: 'flex', alignItems: 'flex-start', gap: 8,
    padding: 10, marginTop: 12,
    background: 'rgba(167,139,250,0.06)',
    border: '1px solid rgba(167,139,250,0.2)',
    borderRadius: 8,
    fontSize: 10, color: '#818cf8', fontWeight: 500, lineHeight: 1.4,
  },
  lockedBox: {
    display: 'flex', flexDirection: 'column', alignItems: 'center',
    padding: 40,
    background: 'rgba(15,23,42,0.5)',
    border: '1px solid rgba(255,255,255,0.06)',
    borderRadius: 12,
  },
  settingCard: {
    background: 'rgba(15,23,42,0.4)',
    border: '1px solid rgba(255,255,255,0.06)',
    borderRadius: 12,
    marginBottom: 12,
    overflow: 'hidden',
  },
  settingCardHead: {
    display: 'flex', alignItems: 'center', gap: 6,
    padding: '12px 14px',
    background: 'rgba(0,0,0,0.2)',
    borderBottom: '1px solid rgba(255,255,255,0.04)',
  },
  settingCardTitle: {
    fontSize: 10, fontWeight: 800, letterSpacing: 1.5, color: '#cbd5e1',
  },
  settingCardBody: { padding: 14, display: 'flex', flexDirection: 'column', gap: 10 },
  field: { display: 'flex', flexDirection: 'column', gap: 5, flex: 1 },
  fieldLabel: { fontSize: 9, fontWeight: 800, letterSpacing: 1, color: '#64748b' },
  input: {
    padding: '10px 12px',
    background: 'rgba(0,0,0,0.3)',
    border: '1px solid rgba(255,255,255,0.08)',
    borderRadius: 8,
    color: '#f1f5f9',
    fontSize: 13,
    fontWeight: 500,
    width: '100%',
  },
  scoringGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 8 },
  scoringTile: {
    display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 6,
    padding: 12,
    background: 'rgba(0,0,0,0.3)',
    border: '1px solid rgba(255,255,255,0.04)',
    borderRadius: 10,
  },
  scoringLabel: { fontSize: 9, fontWeight: 800, letterSpacing: 1, color: '#94a3b8' },
  scoringPts: { fontSize: 8, fontWeight: 800, letterSpacing: 1.5, color: '#475569', fontFamily: "'JetBrains Mono', monospace" },
  bonusRow: {
    display: 'flex', alignItems: 'center', gap: 8,
    padding: 12,
    background: 'rgba(0,0,0,0.2)',
    border: '1px solid',
    borderRadius: 10,
  },
  bonusLabel: { fontSize: 12, fontWeight: 700, color: '#f1f5f9' },
  bonusDesc: { fontSize: 10, color: '#64748b', marginTop: 2, lineHeight: 1.3 },
  switch: {
    width: 36, height: 20, borderRadius: 12,
    border: 'none', position: 'relative',
    transition: 'background 0.2s',
    flexShrink: 0,
  },
  switchKnob: {
    position: 'absolute', top: 2, left: 2,
    width: 16, height: 16, borderRadius: '50%',
    background: '#fff',
    transition: 'transform 0.2s',
    boxShadow: '0 1px 3px rgba(0,0,0,0.3)',
  },
  tieEditor: { display: 'flex', flexDirection: 'column', gap: 6 },
  tieEditorRow: {
    display: 'flex', alignItems: 'center', gap: 8,
    padding: '10px 12px',
    background: 'rgba(0,0,0,0.2)',
    border: '1px solid rgba(255,255,255,0.04)',
    borderRadius: 8,
    fontSize: 12, color: '#cbd5e1', fontWeight: 600,
  },
  iconBtn: {
    width: 24, height: 24, borderRadius: 5,
    background: 'rgba(15,23,42,0.6)',
    border: '1px solid rgba(255,255,255,0.08)',
    color: '#94a3b8',
    fontSize: 11, fontWeight: 800,
  },
  roleCard: {
    display: 'flex', alignItems: 'center', gap: 12,
    padding: 14,
    border: '2px solid',
    borderRadius: 12,
    transition: 'all 0.2s',
  },
  roleIcon: {
    width: 42, height: 42, borderRadius: 10,
    border: '1px solid',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
  },
  activeMark: {
    width: 24, height: 24, borderRadius: '50%',
    background: 'rgba(34,211,238,0.15)',
    border: '1.5px solid currentColor',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
  },
  permsBox: {
    marginTop: 16, padding: 14,
    background: 'rgba(15,23,42,0.4)',
    border: '1px solid rgba(255,255,255,0.06)',
    borderRadius: 12,
  },
  permsTitle: {
    fontSize: 9, fontWeight: 800, letterSpacing: 1.5, color: '#64748b',
    marginBottom: 10,
  },
  permRow: {
    display: 'flex', alignItems: 'center', gap: 8,
    padding: '6px 0',
    fontSize: 11, color: '#cbd5e1', fontWeight: 500,
  },
  quickGrid: { display: 'flex', flexDirection: 'column', gap: 6 },
  quickAction: {
    display: 'flex', alignItems: 'center', gap: 12,
    padding: 12,
    background: 'rgba(15,23,42,0.5)',
    border: '1px solid rgba(255,255,255,0.06)',
    borderRadius: 10,
    transition: 'all 0.2s',
    width: '100%',
  },
  quickIcon: {
    width: 34, height: 34, borderRadius: 8,
    border: '1px solid', display: 'flex', alignItems: 'center', justifyContent: 'center',
  },
  quickLabel: {
    flex: 1, textAlign: 'left',
    fontSize: 13, fontWeight: 700, color: '#cbd5e1',
  },
  quickLockBadge: {
    position: 'absolute', top: -4, right: -4,
    width: 18, height: 18, borderRadius: 5,
    background: '#0a0f1c',
    border: '1px solid rgba(245,158,11,0.5)',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
  },
  quickLockHint: {
    fontSize: 9, fontWeight: 700, color: '#f59e0b',
    letterSpacing: 0.5, marginTop: 2,
  },
  searchWrap: {
    marginBottom: 12,
    display: 'flex', flexDirection: 'column', gap: 6,
  },
  searchBar: {
    display: 'flex', alignItems: 'center', gap: 8,
    padding: '10px 12px',
    background: 'rgba(15,23,42,0.5)',
    border: '1px solid rgba(255,255,255,0.08)',
    borderRadius: 10,
  },
  searchInput: {
    flex: 1, background: 'transparent', border: 'none',
    color: '#f1f5f9', fontSize: 13, fontWeight: 500,
    outline: 'none', padding: 0,
  },
  searchClear: {
    width: 22, height: 22, borderRadius: 5,
    background: 'rgba(15,23,42,0.6)',
    border: '1px solid rgba(255,255,255,0.08)',
    color: '#94a3b8',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
  },
  searchSuggest: {
    background: 'rgba(15,23,42,0.85)',
    border: '1px solid rgba(34,211,238,0.2)',
    borderRadius: 10,
    overflow: 'hidden',
    backdropFilter: 'blur(12px)',
  },
  searchSuggestRow: {
    display: 'flex', alignItems: 'center', gap: 10,
    width: '100%', padding: '10px 12px',
    background: 'transparent', border: 'none',
    borderBottom: '1px solid rgba(255,255,255,0.04)',
  },
  selectedTeamPill: {
    display: 'inline-flex', alignItems: 'center', gap: 8,
    padding: '6px 8px 6px 6px', alignSelf: 'flex-start',
    background: 'rgba(34,211,238,0.1)',
    border: '1px solid rgba(34,211,238,0.4)',
    borderRadius: 18,
  },
  pillClear: {
    width: 18, height: 18, borderRadius: '50%',
    background: 'rgba(34,211,238,0.2)',
    border: 'none',
    color: '#a3e635',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    marginLeft: 2,
  },
  confirmOverlay: {
    position: 'fixed', inset: 0, zIndex: 300,
    background: 'rgba(0,0,0,0.7)',
    backdropFilter: 'blur(8px)',
    WebkitBackdropFilter: 'blur(8px)',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    padding: 20,
    animation: 'slideUp 0.2s ease',
  },
  confirmCard: {
    width: '100%', maxWidth: 360,
    background: '#0a0f1c',
    border: '1px solid rgba(34,211,238,0.25)',
    borderRadius: 16,
    padding: 22,
    display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 10,
    boxShadow: '0 20px 60px rgba(0,0,0,0.6)',
  },
  confirmIcon: {
    width: 48, height: 48, borderRadius: 12,
    border: '1px solid',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    marginBottom: 4,
  },
  confirmTitle: {
    fontSize: 16, fontWeight: 800, color: '#f1f5f9', textAlign: 'center',
  },
  confirmMessage: {
    fontSize: 12, color: '#94a3b8', textAlign: 'center', lineHeight: 1.5,
    marginBottom: 8,
  },
  confirmActions: {
    display: 'flex', gap: 8, width: '100%',
  },
  archiveCard: {
    background: 'rgba(15,23,42,0.5)',
    border: '1px solid rgba(167,139,250,0.15)',
    borderRadius: 12,
    padding: 14,
    width: '100%', textAlign: 'left',
    display: 'flex', flexDirection: 'column', gap: 8,
  },
  archiveHead: {
    display: 'flex', justifyContent: 'space-between', alignItems: 'center',
  },
  archiveBadge: {
    display: 'inline-flex', alignItems: 'center', gap: 4,
    fontSize: 9, fontWeight: 800, letterSpacing: 1, color: '#818cf8',
    padding: '3px 7px',
    background: 'rgba(167,139,250,0.1)',
    border: '1px solid rgba(167,139,250,0.3)',
    borderRadius: 4,
  },
  archiveDate: {
    fontSize: 10, color: '#94a3b8', fontWeight: 600,
    fontFamily: "'JetBrains Mono', monospace",
  },
  archiveTitle: {
    fontSize: 15, fontWeight: 800, color: '#f1f5f9',
  },
  archiveLoc: {
    display: 'inline-flex', alignItems: 'center', gap: 4,
    fontSize: 11, color: '#94a3b8', fontWeight: 500,
  },
  archiveWinner: {
    display: 'flex', alignItems: 'center', gap: 6,
    padding: '8px 10px',
    background: 'rgba(250,204,21,0.06)',
    border: '1px solid rgba(250,204,21,0.2)',
    borderRadius: 8,
    marginTop: 4,
  },
  archiveStats: {
    display: 'flex', gap: 14,
    fontSize: 10, color: '#64748b', fontWeight: 600,
    paddingTop: 6,
    borderTop: '1px solid rgba(255,255,255,0.04)',
  },
  winnerCard: {
    display: 'flex', alignItems: 'center', gap: 12,
    padding: 16,
    background: 'linear-gradient(135deg, rgba(250,204,21,0.12), rgba(250,204,21,0.04))',
    border: '1px solid rgba(250,204,21,0.4)',
    borderRadius: 14,
    marginBottom: 16,
    boxShadow: '0 0 30px rgba(250,204,21,0.1)',
  },
  notifStack: {
    position: 'fixed', top: 70, left: '50%', transform: 'translateX(-50%)',
    width: '100%', maxWidth: 460,
    padding: '0 12px',
    display: 'flex', flexDirection: 'column', gap: 8,
    zIndex: 250,
    pointerEvents: 'none',
  },
  notifCard: {
    pointerEvents: 'auto',
    display: 'flex', alignItems: 'flex-start', gap: 10,
    padding: 12,
    background: 'rgba(10,15,28,0.95)',
    backdropFilter: 'blur(16px)',
    WebkitBackdropFilter: 'blur(16px)',
    border: '1px solid',
    borderRadius: 12,
    cursor: 'pointer',
    animation: 'slideUp 0.3s ease',
  },
  notifIcon: {
    width: 30, height: 30, borderRadius: 8,
    border: '1px solid',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    flexShrink: 0,
  },
  notifLabel: {
    fontSize: 8, fontWeight: 800, letterSpacing: 1.5,
  },
  notifTitle: {
    fontSize: 12, fontWeight: 700, color: '#f1f5f9',
    marginTop: 2,
  },
  notifTeams: {
    fontSize: 10, fontWeight: 600, color: '#94a3b8',
    marginTop: 2,
    fontFamily: "'JetBrains Mono', monospace",
  },
  notifMessage: {
    fontSize: 10, color: '#94a3b8', marginTop: 2,
  },
  notifClose: {
    width: 22, height: 22, borderRadius: 5,
    background: 'rgba(15,23,42,0.6)',
    border: '1px solid rgba(255,255,255,0.08)',
    color: '#94a3b8',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    flexShrink: 0,
  },
  followStar: {
    width: 32, height: 32, borderRadius: 8,
    border: '1.5px solid',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    transition: 'all 0.2s',
    flexShrink: 0,
  },
  navBadge: {
    position: 'absolute', top: -4, right: -8,
    minWidth: 14, height: 14, borderRadius: 7,
    background: '#facc15',
    color: '#0a0a0a',
    fontSize: 9, fontWeight: 800,
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    padding: '0 4px',
  },
  adjustPanel: {
    display: 'flex', alignItems: 'stretch', gap: 6,
    padding: 8,
    background: 'rgba(251,113,133,0.06)',
    border: '1px solid rgba(251,113,133,0.2)',
    borderRadius: 10,
  },
  adjustBtn: {
    flex: 1,
    display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 3,
    padding: '10px 6px',
    background: 'rgba(15,23,42,0.6)',
    border: '1px solid rgba(251,113,133,0.3)',
    borderRadius: 7,
    color: '#fb7185',
    fontSize: 11, fontWeight: 800, letterSpacing: 0.5,
    fontFamily: "'JetBrains Mono', monospace",
  },
  adjustLabel: {
    flex: 1.2,
    display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 2,
    fontSize: 9, fontWeight: 700, letterSpacing: 0.5, color: '#fb7185',
    textAlign: 'center',
  },
  gearBtn: {
    width: 32, height: 32, borderRadius: 8,
    background: 'rgba(15,23,42,0.6)',
    border: '1px solid rgba(255,255,255,0.08)',
    color: '#94a3b8',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    transition: 'all 0.2s',
  },
  gearBtnActive: {
    background: 'rgba(244,114,182,0.12)',
    borderColor: 'rgba(244,114,182,0.4)',
    color: '#f472b6',
    boxShadow: '0 0 16px rgba(244,114,182,0.2)',
  },
  btnLibrary: {
    display: 'inline-flex', alignItems: 'center', gap: 6,
    padding: '11px 14px',
    background: 'rgba(167,139,250,0.1)',
    color: '#818cf8',
    border: '1px solid rgba(167,139,250,0.3)',
    borderRadius: 8,
    fontSize: 11, fontWeight: 800, letterSpacing: 1,
  },
  successPill: {
    display: 'inline-flex', alignItems: 'center', gap: 4,
    padding: '5px 9px',
    background: 'rgba(52,211,153,0.12)',
    border: '1px solid rgba(52,211,153,0.3)',
    borderRadius: 6,
    fontSize: 10, fontWeight: 800, letterSpacing: 0.5, color: '#34d399',
  },
  roleLockBtn: {
    position: 'absolute', top: 8, right: 8,
    width: 22, height: 22, borderRadius: 5,
    background: 'rgba(15,23,42,0.85)',
    border: '1px solid rgba(255,255,255,0.1)',
    color: '#64748b',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
  },
  staffAccessTrigger: {
    display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6,
    width: '100%', padding: '12px',
    background: 'transparent',
    border: '1px dashed rgba(100,116,139,0.4)',
    borderRadius: 10,
    color: '#64748b',
    fontSize: 11, fontWeight: 700, letterSpacing: 0.5,
  },
  staffAccessBox: {
    padding: 14,
    background: 'rgba(34,211,238,0.05)',
    border: '1px solid rgba(34,211,238,0.25)',
    borderRadius: 10,
    display: 'flex', flexDirection: 'column', gap: 8,
  },
  staffAccessTitle: {
    display: 'flex', alignItems: 'center', gap: 6,
    fontSize: 11, fontWeight: 800, letterSpacing: 1.5, color: '#a3e635',
  },
  staffAccessDesc: {
    fontSize: 11, color: '#94a3b8', lineHeight: 1.4,
  },
  // ========== ONBOARDING ==========
  onboardingWrap: {
    minHeight: '100vh',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    padding: '20px 16px',
    position: 'relative',
    zIndex: 2,
  },
  onboardingCard: {
    width: '100%', maxWidth: 380,
    background: 'rgba(15,23,42,0.7)',
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
    border: '1px solid rgba(34,211,238,0.18)',
    borderRadius: 18,
    padding: 24,
    boxShadow: '0 30px 80px rgba(0,0,0,0.5)',
  },
  onbDots: {
    display: 'flex', gap: 6, justifyContent: 'center',
    marginBottom: 18,
  },
  onbDot: {
    width: 24, height: 4, borderRadius: 2,
    transition: 'background 0.3s',
  },
  onbTitle: {
    fontSize: 22, fontWeight: 800, color: '#f1f5f9',
    textAlign: 'center', letterSpacing: -0.5,
  },
  onbSubtitle: {
    fontSize: 12, color: '#94a3b8', textAlign: 'center',
    marginTop: 8, lineHeight: 1.5,
  },
  onbHint: {
    fontSize: 11, color: '#64748b', textAlign: 'center',
  },
  onbDivider: {
    display: 'flex', alignItems: 'center', gap: 10,
    margin: '16px 0',
  },
  onbDividerLine: {
    flex: 1, height: 1, background: 'rgba(255,255,255,0.08)',
  },
  onbDividerText: {
    fontSize: 9, fontWeight: 800, letterSpacing: 1.5, color: '#475569',
  },
  onbScanner: {
    display: 'flex', justifyContent: 'center',
    margin: '20px 0',
  },
  onbScannerFrame: {
    position: 'relative',
    width: 180, height: 180,
    background: 'rgba(0,0,0,0.4)',
    border: '1px solid rgba(34,211,238,0.2)',
    borderRadius: 16,
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    overflow: 'hidden',
  },
  onbScannerCorner1: {
    position: 'absolute', top: 8, left: 8, width: 24, height: 24,
    borderTop: '3px solid #a3e635', borderLeft: '3px solid #a3e635', borderRadius: '4px 0 0 0',
  },
  onbScannerCorner2: {
    position: 'absolute', top: 8, right: 8, width: 24, height: 24,
    borderTop: '3px solid #a3e635', borderRight: '3px solid #a3e635', borderRadius: '0 4px 0 0',
  },
  onbScannerCorner3: {
    position: 'absolute', bottom: 8, left: 8, width: 24, height: 24,
    borderBottom: '3px solid #a3e635', borderLeft: '3px solid #a3e635', borderRadius: '0 0 0 4px',
  },
  onbScannerCorner4: {
    position: 'absolute', bottom: 8, right: 8, width: 24, height: 24,
    borderBottom: '3px solid #a3e635', borderRight: '3px solid #a3e635', borderRadius: '0 0 4px 0',
  },
  onbScannerLine: {
    position: 'absolute', left: 16, right: 16,
    height: 2, background: 'linear-gradient(90deg, transparent, #a3e635, transparent)',
    boxShadow: '0 0 12px #a3e635',
    animation: 'scanLine 1.5s ease-in-out infinite',
  },
  legalScroll: {
    maxHeight: 220,
    overflowY: 'auto',
    background: 'rgba(0,0,0,0.3)',
    border: '1px solid rgba(255,255,255,0.06)',
    borderRadius: 10,
    padding: 14,
    marginTop: 14,
    fontSize: 11,
    color: '#cbd5e1',
    lineHeight: 1.5,
  },
  legalP: {
    margin: '0 0 12px 0',
  },
  legalCheck: {
    display: 'flex', alignItems: 'flex-start', gap: 8,
    marginTop: 12,
    fontSize: 11, color: '#cbd5e1', lineHeight: 1.4,
    cursor: 'pointer',
  },
  legalCheckbox: {
    width: 18, height: 18, borderRadius: 4,
    border: '1.5px solid',
    flexShrink: 0,
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    transition: 'all 0.15s',
  },
  permCard: {
    display: 'flex', alignItems: 'center', gap: 10,
    padding: 12, marginTop: 10,
    background: 'rgba(0,0,0,0.3)',
    border: '1px solid rgba(255,255,255,0.06)',
    borderRadius: 10,
  },
  permIcon: {
    width: 36, height: 36, borderRadius: 9,
    border: '1px solid',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    flexShrink: 0,
  },
  permTitle: {
    fontSize: 12, fontWeight: 700, color: '#f1f5f9',
  },
  permDesc: {
    fontSize: 10, color: '#64748b', marginTop: 2, lineHeight: 1.3,
  },
  permBtn: {
    padding: '6px 10px',
    background: 'rgba(15,23,42,0.6)',
    border: '1px solid rgba(255,255,255,0.08)',
    borderRadius: 6,
    fontSize: 10, fontWeight: 800, letterSpacing: 0.5,
  },
  // ========== ANNOUNCEMENT BAR ==========
  annBar: {
    display: 'flex', alignItems: 'center', gap: 8,
    padding: '8px 14px',
    border: '1px solid',
    borderLeft: 'none', borderRight: 'none',
    overflow: 'hidden',
    fontSize: 11, fontWeight: 600,
    animation: 'slideUp 0.3s ease',
  },
  annDot: {
    width: 6, height: 6, borderRadius: '50%',
    flexShrink: 0,
    animation: 'pulse 1.8s ease-in-out infinite',
  },
  annText: {
    flex: 1, minWidth: 0,
    overflow: 'hidden', textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  annCount: {
    fontSize: 9, fontWeight: 800, letterSpacing: 0.5,
    fontFamily: "'JetBrains Mono', monospace",
    flexShrink: 0,
  },
  annListItem: {
    display: 'flex', alignItems: 'center', gap: 8,
    padding: '8px 10px',
    background: 'rgba(0,0,0,0.2)',
    border: '1px solid',
    borderRadius: 8,
  },
  annListType: {
    fontSize: 8, fontWeight: 800, letterSpacing: 1,
    padding: '3px 6px', borderRadius: 3,
    flexShrink: 0,
  },
  annListMsg: {
    flex: 1, minWidth: 0,
    fontSize: 11, color: '#cbd5e1', lineHeight: 1.3,
  },
  // ========== SPONSOR TICKER ==========
  sponsorBar: {
    position: 'fixed', bottom: 80, left: '50%', transform: 'translateX(-50%)',
    width: '100%', maxWidth: 480,
    height: 28,
    display: 'flex', alignItems: 'center', gap: 8,
    background: 'rgba(5,8,16,0.92)',
    backdropFilter: 'blur(12px)',
    WebkitBackdropFilter: 'blur(12px)',
    borderTop: '1px solid rgba(255,255,255,0.06)',
    borderBottom: '1px solid rgba(255,255,255,0.06)',
    overflow: 'hidden',
    zIndex: 49,
  },
  sponsorLabel: {
    fontSize: 8, fontWeight: 800, letterSpacing: 1.5, color: '#475569',
    paddingLeft: 12, flexShrink: 0,
    fontFamily: "'JetBrains Mono', monospace",
  },
  sponsorTrack: {
    flex: 1, overflow: 'hidden',
    maskImage: 'linear-gradient(to right, transparent, black 5%, black 95%, transparent)',
    WebkitMaskImage: 'linear-gradient(to right, transparent, black 5%, black 95%, transparent)',
  },
  sponsorScroll: {
    display: 'flex', alignItems: 'center', gap: 0,
    width: 'max-content',
  },
  sponsorItem: {
    display: 'flex', alignItems: 'center', gap: 12,
    padding: '0 6px', flexShrink: 0,
  },
  sponsorName: {
    fontSize: 11, fontWeight: 600, color: '#94a3b8',
    whiteSpace: 'nowrap',
  },
  sponsorSep: {
    color: '#334155', fontSize: 12, fontWeight: 800,
  },
  levelGrid: {
    display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: 4,
  },
  levelBtn: {
    padding: '10px 6px',
    border: '1.5px solid',
    borderRadius: 7,
    fontSize: 12, fontWeight: 800, letterSpacing: 0.5,
    transition: 'all 0.2s',
    fontFamily: "'JetBrains Mono', monospace",
  },
  rankingGrid: {
    display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 5,
  },
  rankingChip: {
    display: 'flex', alignItems: 'center', gap: 6,
    padding: '8px 10px',
    border: '1px solid',
    borderRadius: 7,
    transition: 'all 0.2s',
  },
  rankingDot: {
    width: 6, height: 6, borderRadius: '50%',
    flexShrink: 0,
    marginLeft: 'auto',
  },
  noRankingCard: {
    display: 'flex', flexDirection: 'column', alignItems: 'center',
    padding: '40px 24px',
    background: 'rgba(15,23,42,0.5)',
    border: '1px solid rgba(167,139,250,0.2)',
    borderRadius: 14,
  },
  scheduleActions: {
    display: 'flex', gap: 8, marginBottom: 12,
  },
  btnGenerate: {
    display: 'inline-flex', alignItems: 'center', gap: 6,
    padding: '11px 14px',
    background: 'rgba(167,139,250,0.1)',
    color: '#818cf8',
    border: '1px solid rgba(167,139,250,0.3)',
    borderRadius: 8,
    fontSize: 11, fontWeight: 800, letterSpacing: 1,
  },
  fieldsBar: {
    display: 'flex', alignItems: 'center', gap: 10,
    padding: '8px 12px', marginBottom: 12,
    background: 'rgba(52,211,153,0.06)',
    border: '1px solid rgba(52,211,153,0.2)',
    borderRadius: 8,
  },
  fieldsBarLabel: {
    fontSize: 9, fontWeight: 800, letterSpacing: 1.5, color: '#34d399',
  },
  fieldsList: { display: 'flex', gap: 5, flexWrap: 'wrap', flex: 1 },
  fieldChip: {
    padding: '3px 8px',
    background: 'rgba(52,211,153,0.12)',
    border: '1px solid rgba(52,211,153,0.3)',
    borderRadius: 4,
    fontSize: 10, fontWeight: 700, color: '#34d399', letterSpacing: 0.5,
    fontFamily: "'JetBrains Mono', monospace",
  },
  timeSlotHeader: {
    display: 'flex', alignItems: 'center', gap: 8,
    marginBottom: 10,
  },
  timeSlotLabel: {
    fontSize: 12, fontWeight: 800, color: '#34d399', letterSpacing: 1,
    fontFamily: "'JetBrains Mono', monospace",
  },
  timeSlotLine: {
    flex: 1, height: 1, background: 'linear-gradient(90deg, rgba(52,211,153,0.3), transparent)',
  },
  scheduleRow: {
    display: 'flex', alignItems: 'center', gap: 10,
    padding: 10,
    background: 'rgba(15,23,42,0.5)',
    border: '1px solid rgba(255,255,255,0.06)',
    borderRadius: 10,
    width: '100%', textAlign: 'left',
  },
  scheduleField: {
    width: 36, height: 36, borderRadius: 8,
    background: 'rgba(52,211,153,0.1)',
    border: '1px solid rgba(52,211,153,0.3)',
    color: '#34d399',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    fontSize: 11, fontWeight: 800, letterSpacing: 0.5,
    fontFamily: "'JetBrains Mono', monospace",
    flexShrink: 0,
  },
  scheduleTeams: {
    flex: 1, minWidth: 0,
    display: 'flex', flexDirection: 'column', gap: 4,
  },
  scheduleTeam: {
    display: 'flex', alignItems: 'center', gap: 8,
  },
  scheduleTeamName: {
    fontSize: 12, fontWeight: 700, color: '#f1f5f9',
    overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
  },
  scheduleVs: {
    fontSize: 8, fontWeight: 800, color: '#475569', letterSpacing: 1,
    paddingLeft: 34,
  },
  scheduleMeta: {
    display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: 6,
  },
  schedulePool: {
    fontSize: 9, fontWeight: 800, color: '#94a3b8', letterSpacing: 0.5,
    fontFamily: "'JetBrains Mono', monospace",
  },
  matchPreview: {
    display: 'grid', gridTemplateColumns: '1fr auto 1fr', alignItems: 'center', gap: 12,
    padding: 14,
    background: 'rgba(0,0,0,0.3)',
    border: '1px solid rgba(255,255,255,0.06)',
    borderRadius: 10,
  },
  previewSide: {
    display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 6,
  },
  previewName: {
    fontSize: 11, fontWeight: 700, color: '#f1f5f9', textAlign: 'center', lineHeight: 1.2,
  },
  previewVs: {
    fontSize: 11, fontWeight: 800, color: '#475569', letterSpacing: 1,
    fontFamily: "'JetBrains Mono', monospace",
  },
  fieldError: {
    fontSize: 10, color: '#f87171', marginTop: 4, fontWeight: 600,
  },
  fieldsGrid: {
    display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 6,
  },
  fieldEditChip: {
    display: 'flex', alignItems: 'center', gap: 6,
    padding: '8px 10px',
    background: 'rgba(52,211,153,0.06)',
    border: '1px solid rgba(52,211,153,0.2)',
    borderRadius: 8,
  },
  fieldEditRemove: {
    background: 'rgba(220,38,38,0.1)',
    border: '1px solid rgba(220,38,38,0.3)',
    color: '#f87171',
    width: 20, height: 20, borderRadius: 4,
    display: 'flex', alignItems: 'center', justifyContent: 'center',
  },
  knockoutBadge: {
    display: 'inline-flex', alignItems: 'center', gap: 4,
    fontSize: 9, fontWeight: 800, letterSpacing: 1, color: '#f59e0b',
    padding: '2px 7px',
    background: 'rgba(245,158,11,0.12)',
    border: '1px solid rgba(245,158,11,0.4)',
    borderRadius: 3,
  },
  qualifyGrid: {
    display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 6,
  },
  qualifyBtn: {
    padding: '10px 8px',
    border: '1.5px solid',
    borderRadius: 8,
    fontSize: 12, fontWeight: 800, letterSpacing: 0.5,
    transition: 'all 0.2s',
    fontFamily: "'JetBrains Mono', monospace",
  },
  bracketContainer: {
    overflowX: 'auto',
    paddingBottom: 16,
  },
  bracketGrid: {
    display: 'flex',
    gap: 24,
    minWidth: 'max-content',
    alignItems: 'stretch',
    paddingTop: 8,
  },
  bracketColumn: {
    display: 'flex', flexDirection: 'column',
    gap: 12, justifyContent: 'space-around',
    minWidth: 180,
  },
  bracketColumnLabel: {
    fontSize: 9, fontWeight: 800, letterSpacing: 1.5, color: '#f59e0b',
    textAlign: 'center', marginBottom: 6,
    paddingBottom: 6, borderBottom: '1px solid rgba(245,158,11,0.2)',
  },
  bracketMatch: {
    background: 'rgba(15,23,42,0.6)',
    border: '1px solid rgba(255,255,255,0.06)',
    borderRadius: 8,
    padding: 8,
    display: 'flex', flexDirection: 'column', gap: 6,
    cursor: 'pointer',
    width: '100%', textAlign: 'left',
  },
  bracketMatchLive: {
    borderColor: 'rgba(34,211,238,0.4)',
    background: 'linear-gradient(135deg, rgba(34,211,238,0.1), rgba(15,23,42,0.6))',
  },
  bracketMatchDone: {
    borderColor: 'rgba(52,211,153,0.3)',
  },
  bracketTeam: {
    display: 'flex', alignItems: 'center', gap: 6,
    padding: '4px 6px', borderRadius: 4,
  },
  bracketTeamWin: {
    background: 'rgba(52,211,153,0.08)',
  },
  bracketTeamLose: {
    opacity: 0.5,
  },
  bracketName: {
    flex: 1, minWidth: 0,
    fontSize: 11, fontWeight: 700, color: '#f1f5f9',
    overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
  },
  bracketScore: {
    fontSize: 13, fontWeight: 800, color: '#a3e635',
    fontFamily: "'JetBrains Mono', monospace",
    minWidth: 18, textAlign: 'right',
  },
  bracketMeta: {
    display: 'flex', justifyContent: 'space-between',
    fontSize: 8, color: '#64748b', fontWeight: 700, letterSpacing: 0.5,
    paddingTop: 4, borderTop: '1px solid rgba(255,255,255,0.04)',
  },
  modeToggle: {
    display: 'flex', gap: 6, marginBottom: 14,
    padding: 4,
    background: 'rgba(15,23,42,0.5)',
    border: '1px solid rgba(255,255,255,0.06)',
    borderRadius: 10,
  },
  modeBtn: {
    flex: 1, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: 6,
    padding: '9px 12px',
    background: 'transparent',
    border: 'none',
    borderRadius: 7,
    fontSize: 11, fontWeight: 800, letterSpacing: 1, color: '#64748b',
    transition: 'all 0.2s',
  },
  modeBtnActive: {
    background: 'rgba(245,158,11,0.12)',
    color: '#f59e0b',
    boxShadow: '0 0 12px rgba(245,158,11,0.15)',
  },
  durationsList: {
    display: 'flex', flexDirection: 'column', gap: 5,
  },
  durationRow: {
    display: 'flex', alignItems: 'center', gap: 8,
    padding: '8px 10px',
    border: '1px solid',
    borderRadius: 8,
  },
  durationCat: {
    fontSize: 12, fontWeight: 800, letterSpacing: 0.5,
    fontFamily: "'JetBrains Mono', monospace",
    minWidth: 44,
  },
  durationActiveBadge: {
    fontSize: 8, fontWeight: 800, letterSpacing: 1, color: '#a3e635',
    padding: '2px 5px',
    background: 'rgba(34,211,238,0.12)',
    border: '1px solid rgba(34,211,238,0.3)',
    borderRadius: 3,
  },
  durationStepper: {
    display: 'flex', alignItems: 'center', gap: 4,
    marginLeft: 'auto',
  },
  durationInput: {
    width: 44, textAlign: 'center',
    padding: '6px 4px',
    background: 'rgba(0,0,0,0.4)',
    border: '1px solid rgba(255,255,255,0.08)',
    borderRadius: 6,
    color: '#f1f5f9',
    fontSize: 13, fontWeight: 700,
    fontFamily: "'JetBrains Mono', monospace",
    MozAppearance: 'textfield',
  },
  durationUnit: {
    fontSize: 9, fontWeight: 700, color: '#64748b', letterSpacing: 0.5,
    marginLeft: 2,
  },
// ===== Cartes de match (manquantes) =====
liveCard: {
  display: 'flex', flexDirection: 'column', gap: 10,
  padding: 14,
  background: 'linear-gradient(135deg, rgba(34,211,238,0.08), rgba(15,23,42,0.6))',
  border: '1px solid rgba(34,211,238,0.3)',
  borderRadius: 14,
  color: '#f1f5f9',
  cursor: 'pointer',
  textAlign: 'left',
  width: '100%',
},
liveTopRow: {
  display: 'flex', justifyContent: 'space-between', alignItems: 'center',
},
livePill: {
  display: 'inline-flex', alignItems: 'center', gap: 5,
  padding: '4px 8px',
  background: 'rgba(34,211,238,0.15)',
  border: '1px solid rgba(34,211,238,0.4)',
  borderRadius: 4,
  color: '#a3e635',
},
livePulse: {
  width: 6, height: 6, borderRadius: '50%',
  background: '#a3e635',
  animation: 'pulse 1.5s ease-in-out infinite',
  flexShrink: 0,
},
liveField: {
  display: 'inline-flex', alignItems: 'center', gap: 3,
  fontSize: 10, color: '#94a3b8',
  fontFamily: "'JetBrains Mono', monospace",
},
liveScore: {
  display: 'flex', alignItems: 'center', justifyContent: 'space-between',
  gap: 12,
},
liveTeam: {
  display: 'flex', alignItems: 'center', gap: 8, flex: 1,
},
liveTeamName: {
  fontSize: 13, fontWeight: 800, color: '#f1f5f9',
  fontFamily: "'JetBrains Mono', monospace",
  maxWidth: 120, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
},
liveScoreNum: {
  fontSize: 22, fontWeight: 800, color: '#a3e635',
  fontFamily: "'JetBrains Mono', monospace",
},
upcomingCard: {
  display: 'flex', alignItems: 'center', gap: 10,
  padding: 12,
  background: 'rgba(15,23,42,0.5)',
  border: '1px solid rgba(255,255,255,0.06)',
  borderRadius: 10,
  color: '#f1f5f9',
  cursor: 'pointer',
  textAlign: 'left',
  width: '100%',
},
upcomingTime: {
  display: 'flex', alignItems: 'center', gap: 4,
  minWidth: 56,
},
upcomingMid: {
  flex: 1, minWidth: 0,
  display: 'flex', flexDirection: 'column', gap: 2,
},
upcomingTeams: {
  display: 'flex', alignItems: 'center', gap: 6,
},
upcomingTeamName: {
  fontSize: 12, fontWeight: 700, color: '#f1f5f9',
  fontFamily: "'JetBrains Mono', monospace",
},
upcomingMeta: {
  fontSize: 9, color: '#64748b',
  display: 'flex', alignItems: 'center', gap: 6,
  fontFamily: "'JetBrains Mono', monospace",
},
matchListCard: {
  display: 'flex', alignItems: 'center', gap: 8,
  padding: 12,
  background: 'rgba(15,23,42,0.5)',
  border: '1px solid rgba(255,255,255,0.06)',
  borderRadius: 10,
  color: '#f1f5f9',
  cursor: 'pointer',
  textAlign: 'left',
  width: '100%',
},
matchListLeft: {
  display: 'flex', alignItems: 'center', gap: 4,
  minWidth: 60,
},
matchListMid: {
  flex: 1, minWidth: 0,
  display: 'flex', alignItems: 'center', justifyContent: 'space-between',
  gap: 8,
},
matchListSide: {
  display: 'flex', alignItems: 'center', gap: 6, flex: 1, minWidth: 0,
},
matchListName: {
  fontSize: 12, fontWeight: 700, color: '#f1f5f9',
  fontFamily: "'JetBrains Mono', monospace",
  overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
},
matchListScore: {
  fontSize: 13, fontWeight: 800,
  fontFamily: "'JetBrains Mono', monospace",
  minWidth: 60, textAlign: 'center',
},
matchListRight: {
  display: 'inline-flex', alignItems: 'center', gap: 3,
  fontSize: 9, color: '#94a3b8',
  fontFamily: "'JetBrains Mono', monospace",
},};
